# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rgig_cpp <- function(lam, chi, psi) {
    .Call(`_famr_rgig_cpp`, lam, chi, psi)
}

update_zeta <- function(psi, q, global_shrink = 1) {
    .Call(`_famr_update_zeta`, psi, q, global_shrink)
}

update_psi <- function(B, Sigmainv, B0, zeta, q, p) {
    .Call(`_famr_update_psi`, B, Sigmainv, B0, zeta, q, p)
}

update_B_TPBN <- function(X, Y, Sigma, B0, psi, q, p) {
    .Call(`_famr_update_B_TPBN`, X, Y, Sigma, B0, psi, q, p)
}

update_eta_gibbs_cpp <- function(eta, B, Theta, Sigmay_inv, sigmax_sqinv, Y, X, K, p, t, n, q, q_int, uid, Z, Z_int) {
    .Call(`_famr_update_eta_gibbs_cpp`, eta, B, Theta, Sigmay_inv, sigmax_sqinv, Y, X, K, p, t, n, q, q_int, uid, Z, Z_int)
}

submat_cpp <- function(M, idx, idy) {
    .Call(`_famr_submat_cpp`, M, idx, idy)
}

impute_X_lod_cpp <- function(eta, Theta, X, sigmax_sqinv, n, Ilod, llod, ulod) {
    .Call(`_famr_impute_X_lod_cpp`, eta, Theta, X, sigmax_sqinv, n, Ilod, llod, ulod)
}

impute_Ymis_cpp <- function(Y, M, Sigma, O, n, t) {
    .Call(`_famr_impute_Ymis_cpp`, Y, M, Sigma, O, n, t)
}

impute_Yprobit_cpp <- function(Y, M, Sigma, Yraw, binary, n, t) {
    .Call(`_famr_impute_Yprobit_cpp`, Y, M, Sigma, Yraw, binary, n, t)
}

update_Theta_MGP_cpp <- function(eta, sigmax_sqinv, phi, delta, tau, K, p, X) {
    .Call(`_famr_update_Theta_MGP_cpp`, eta, sigmax_sqinv, phi, delta, tau, K, p, X)
}

update_phi_MGP_cpp <- function(Theta, tau, K, p, v1, v2) {
    .Call(`_famr_update_phi_MGP_cpp`, Theta, tau, K, p, v1, v2)
}

update_delta_MGP_cpp <- function(delta, tau, Theta, phi, K, p) {
    .Call(`_famr_update_delta_MGP_cpp`, delta, tau, Theta, phi, K, p)
}

