# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_intercept_cpp <- function(alpha, mu, v, Y, id, uid, Sigma, Sigmainv, v0, s0, random_intercept, n, N, q) {
    invisible(.Call(`_famr_update_intercept_cpp`, alpha, mu, v, Y, id, uid, Sigma, Sigmainv, v0, s0, random_intercept, n, N, q))
}

update_B_DL_cpp <- function(B, Y, X, Sigma_inv, V, n, q, p) {
    invisible(.Call(`_famr_update_B_DL_cpp`, B, Y, X, Sigma_inv, V, n, q, p))
}

update_nu_DL_cpp <- function(nu, B, psi, zeta, p, q) {
    invisible(.Call(`_famr_update_nu_DL_cpp`, nu, B, psi, zeta, p, q))
}

update_psi_DL_cpp <- function(psi, B, p, q) {
    invisible(.Call(`_famr_update_psi_DL_cpp`, psi, B, p, q))
}

update_zeta_DL_cpp <- function(zeta, psi, B, nu) {
    invisible(.Call(`_famr_update_zeta_DL_cpp`, zeta, psi, B, nu))
}

update_zeta_TPBN_cpp <- function(psi, q, global_shrink = 1) {
    .Call(`_famr_update_zeta_TPBN_cpp`, psi, q, global_shrink)
}

update_psi_TPBN_cpp <- function(B, Sigmainv, zeta, q, p) {
    .Call(`_famr_update_psi_TPBN_cpp`, B, Sigmainv, zeta, q, p)
}

update_B_TPBN_cpp <- function(X, Y, Sigma, psi, p, q) {
    .Call(`_famr_update_B_TPBN_cpp`, X, Y, Sigma, psi, p, q)
}

update_B_GP_cpp <- function(Y, time, Bt_eta_k, eta, C_inv, psi, id, sinv, Sigma, K, q, T, n) {
    .Call(`_famr_update_B_GP_cpp`, Y, time, Bt_eta_k, eta, C_inv, psi, id, sinv, Sigma, K, q, T, n)
}

update_B_GP_amplitude_cpp <- function(psi_sq, zeta, tau_sq, phi, K, q, T, Ci, Si, B) {
    .Call(`_famr_update_B_GP_amplitude_cpp`, psi_sq, zeta, tau_sq, phi, K, q, T, Ci, Si, B)
}

update_eta_mh_cpp <- function(eta, B, Theta, Omega, Sigmay_inv, sigmax_sqinv, Y, X, Z_int, uid, id, K, p, t, n, q_int, n_accepted, eps, A, b, lpmf, s, adaptiveM = TRUE, adaptiveMWG = FALSE, batch_size = 50L) {
    invisible(.Call(`_famr_update_eta_mh_cpp`, eta, B, Theta, Omega, Sigmay_inv, sigmax_sqinv, Y, X, Z_int, uid, id, K, p, t, n, q_int, n_accepted, eps, A, b, lpmf, s, adaptiveM, adaptiveMWG, batch_size))
}

rgig_cpp <- function(lam, psi, chi) {
    .Call(`_famr_rgig_cpp`, lam, psi, chi)
}

rig_cpp <- function(mu) {
    .Call(`_famr_rig_cpp`, mu)
}

submat_cpp <- function(M, idx, idy) {
    .Call(`_famr_submat_cpp`, M, idx, idy)
}

impute_X_lod_cpp <- function(eta, Theta, X, sigmax_sqinv, n, Ilod, llod, ulod) {
    .Call(`_famr_impute_X_lod_cpp`, eta, Theta, X, sigmax_sqinv, n, Ilod, llod, ulod)
}

impute_Ymis_cpp <- function(Y, M, Sigma, O, n, t) {
    .Call(`_famr_impute_Ymis_cpp`, Y, M, Sigma, O, n, t)
}

impute_Yprobit_cpp <- function(Y, M, Sigma, Yraw, binary, n, t) {
    .Call(`_famr_impute_Yprobit_cpp`, Y, M, Sigma, Yraw, binary, n, t)
}

update_Omega_TPBN_cpp <- function(Omega, X, Y, Sigma, psi) {
    .Call(`_famr_update_Omega_TPBN_cpp`, Omega, X, Y, Sigma, psi)
}

update_Omega_psi_cpp <- function(psir, psic, Omega, Sigmainv, zetar, zetac, K, q) {
    invisible(.Call(`_famr_update_Omega_psi_cpp`, psir, psic, Omega, Sigmainv, zetar, zetac, K, q))
}

update_Omega_zeta_cpp <- function(zeta, psi, K, global_shrink = 1) {
    invisible(.Call(`_famr_update_Omega_zeta_cpp`, zeta, psi, K, global_shrink))
}

predict_interactions_cpp <- function(Y, X, Omega, n, q) {
    invisible(.Call(`_famr_predict_interactions_cpp`, Y, X, Omega, n, q))
}

update_Theta_MGP_cpp <- function(eta, sigmax_sqinv, phi, delta, tau, K, p, X) {
    .Call(`_famr_update_Theta_MGP_cpp`, eta, sigmax_sqinv, phi, delta, tau, K, p, X)
}

update_phi_MGP_cpp <- function(Theta, tau, K, p) {
    .Call(`_famr_update_phi_MGP_cpp`, Theta, tau, K, p)
}

update_delta_MGP_cpp <- function(delta, tau, Theta, phi, K, p, a1 = 2.0, a2 = 3.0) {
    .Call(`_famr_update_delta_MGP_cpp`, delta, tau, Theta, phi, K, p, a1, a2)
}

update_tau_DL_cpp <- function(tau, Theta, phi, omega, p, K) {
    invisible(.Call(`_famr_update_tau_DL_cpp`, tau, Theta, phi, omega, p, K))
}

update_phi_DL_cpp <- function(phi, Theta, p, K) {
    invisible(.Call(`_famr_update_phi_DL_cpp`, phi, Theta, p, K))
}

update_omega_DL_cpp <- function(omega, phi, Theta, tau) {
    invisible(.Call(`_famr_update_omega_DL_cpp`, omega, phi, Theta, tau))
}

update_Theta_mh_cpp <- function(Theta, sigmax_sqinv, X, V0, n_accepted, eps, s, adaptiveMWG = TRUE) {
    invisible(.Call(`_famr_update_Theta_mh_cpp`, Theta, sigmax_sqinv, X, V0, n_accepted, eps, s, adaptiveMWG))
}

update_random_intercept_cpp <- function(xi, Y, id, uid, Sigma, sigmay_sqinv, nu_sqinv, q, n) {
    invisible(.Call(`_famr_update_random_intercept_cpp`, xi, Y, id, uid, Sigma, sigmay_sqinv, nu_sqinv, q, n))
}

